### ISSUE TITLE
Support generic types via TypeAdapters

### ISSUE THREAD

**Issue by nsk-mironov** [joomcode/smuggler#23]
The following cases should be supported:
1. Unbound generics
```kotlin
class OptionalTypeAdapter<T> : TypeAdapter<Optional<T>>
```

2. Bound generics
```kotlin
class OptionalTypeAdapter<T : Parcelable> : TypeAdapter<Optional<T>>
```

3. Raw types
```kotlin
class OptionalTypeAdapter : TypeAdapter<Optional<*>>
```

4. Parameterized generics
```kotlin
class OptionalTypeAdapter : TypeAdapter<Optional<Parcelable>>
```

5. Nested generics
```kotlin
class OptionalTypeAdapter : TypeAdapter<Optional<List<Parcelable>>>
```

**Comment by meggamind** [comment]
@nsk-mironov : Can you help me out with this, I want to contribute to this issue

**Comment by nsk-mironov** [comment]
Closing the issue as we don't use the library anymore and we don't have plans on supporting it.
